# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6e90d62449d11d5c5a898c65b6a6c0e62603bd61083eecb01ccb455f8d5c6e1cfade7be3784f28e912c5dd8c0f9708c9507dac752b7315824dd2ea9b3f01175

test:
  secret_key_base: a15aca53c61e94ecd85b35c249e98d0ee63207dfe81360b9396c2f7d6afc2fc78d2e536855633ac69fb15f55523f4863f402c2c9ea99b961cdbcc8129b11261a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
